// Sport ID to name mapping (partial list of common sports)
export const WHOOP_SPORTS: Record<number, string> = {
  0: "Running",
  1: "Cycling",
  16: "Baseball",
  17: "Basketball",
  18: "Rowing",
  19: "Fencing",
  20: "Field Hockey",
  21: "Football",
  22: "Golf",
  24: "Ice Hockey",
  25: "Lacrosse",
  27: "Rugby",
  28: "Sailing",
  29: "Skiing",
  30: "Soccer",
  31: "Softball",
  32: "Squash",
  33: "Swimming",
  34: "Tennis",
  35: "Track & Field",
  36: "Volleyball",
  37: "Water Polo",
  38: "Wrestling",
  39: "Boxing",
  42: "Dance",
  43: "Pilates",
  44: "Yoga",
  45: "Weightlifting",
  47: "Cross Country Skiing",
  48: "Functional Fitness",
  49: "Duathlon",
  51: "Gymnastics",
  52: "Hiking",
  53: "Horseback Riding",
  55: "Kayaking",
  56: "Martial Arts",
  57: "Mountain Biking",
  59: "Powerlifting",
  60: "Rock Climbing",
  62: "Snowboarding",
  63: "Surfing",
  64: "Triathlon",
  65: "Walking",
  66: "CrossFit",
  70: "High Intensity Interval Training",
  71: "Spin",
  73: "Jogging",
  74: "Obstacle Course Racing",
  75: "Paddle Boarding",
  76: "Paddling",
  82: "Assault Bike",
  84: "Kickboxing",
  85: "Stretching",
  86: "Training",
  87: "Meditation",
  88: "Other",
  126: "Breathwork",
  260: "Jump Rope",
  261: "Stairmaster",
  264: "HYROX",
  270: "Cleaning",
};

export function getSportName(sportId: number): string {
  return WHOOP_SPORTS[sportId] ?? `Sport ${sportId}`;
}
