name = "engine"
main = "src/index.ts"
compatibility_date = "2023-12-01"
workers_dev = false


[env.production]
name = "engine"
route = { pattern = "engine.mapyourlife.org/*", zone_name = "mapyourlife.org/" }

kv_namespaces = [
  { binding = "KV", id = "79b44b6de25244ecb6372b48885087b5" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "", jurisdiction = "us" }
]

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.mapyourlife.org/*", zone_name = "mapyourlife.org/" }

kv_namespaces = [
  { binding = "KV", id = "ce5d736378314e9d90028390a8d27d12" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "", jurisdiction = "us" }
]