module.exports = {
  apps: [
    {
      name: "website",
      script: "bun",
      args: "run start",
      cwd: "/home/github-runner/actions-runner/_work/map/map/apps/website",
      env: { NODE_ENV: "production" },
      max_memory_restart: "1G",
      error_file: "/var/log/website-error.log",
      out_file: "/var/log/website-out.log",
      restart_delay: 4000,
      max_restarts: 10,
    },
    {
      name: "dashboard",
      script: "bun",
      args: "run start",
      cwd: "/home/github-runner/actions-runner/_work/map/map/apps/dashboard",
      env: { NODE_ENV: "production" },
      max_memory_restart: "1G",
      error_file: "/var/log/dashboard-error.log",
      out_file: "/var/log/dashboard-out.log",
      restart_delay: 4000,
      max_restarts: 10,
    },
    {
      name: "express",
      script: "bun",
      args: "run serve",
      cwd: "/home/github-runner/actions-runner/_work/map/map/apps/express",
      env: { NODE_ENV: "production" },
      max_memory_restart: "1G",
      error_file: "/var/log/express-error.log",
      out_file: "/var/log/express-out.log",
      restart_delay: 4000,
      max_restarts: 10,
    },
    {
      name: "email",
      script: "bun",
      args: "run start",
      cwd: "/home/github-runner/actions-runner/_work/map/map/packages/email",
      env: { NODE_ENV: "production" },
      max_memory_restart: "512M",
      error_file: "/var/log/email-error.log",
      out_file: "/var/log/email-out.log",
      restart_delay: 4000,
      max_restarts: 10,
    },
  ],
};
